name: "PR Title Checker"
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v3.4.2
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            test
            chore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

